### ISSUE TITLE
PHP support?

### ISSUE THREAD

**Issue by djmtype** [asuh/sage-starter#2]
**Cannot GET /**

Does this Gulp Boilerplate support PHP files? Or is **gulp-connect-php** and **http-proxy** required? I'm using MAMP Pro. Inside the gulpfile.js I specified `.php` wherever `.html` was present.

```
  "config": {
    "devUrl": "http://sage-starter.dev:8888"
  }
```

**Comment by Drixled** [comment]
Just replace the **server** option on the gulp watch function with the [proxy](https://browsersync.io/docs/options#option-proxy) option.

Like:
```javascript
gulp.task('watch', function() {
  browserSync.init({
    files: ['*.html'],
    proxy: "yoursite.dev",
    // server: {
    //     baseDir: "./"
    // }
    //files: ['{lib,templates}/**/*.php', '*.php'],
    //proxy: config.devUrl,
    //snippetOptions: {
    //  whitelist: ['/wp-admin/admin-ajax.php'],
    //  blacklist: ['/wp-admin/**']
    //}
  });
  gulp.watch([path.source + 'styles/**/*'], ['styles']);
  gulp.watch([path.source + 'scripts/**/*'], ['lint', 'scripts']);
  gulp.watch([path.source + 'fonts/**/*'], ['fonts']);
  gulp.watch([path.source + 'images/**/*'], ['images']);
  gulp.watch([path.source + 'images/sprite/**/*'], ['svg']);
  gulp.watch(['bower.json', 'assets/manifest.json'], ['build']);
});


```

**Comment by djmtype** [comment]
Thanks. Yes, of course. As given by example in the browser-sync docs. [https://browsersync.io/docs/gulp](https://browsersync.io/docs/gulp)

**Comment by Drixled** [comment]
Sorry but the solution that I provide din't work, the gulp script breaks. Did you solve the problem afterwards?

**Comment by djmtype** [comment]
I could've sworn it was working when I ran `gulp watch`, but now the browser gets stuck at the  progress wheel and the site never renders in the browser. Running `gulp` produces this error: `error  'paths' is assigned a value but never used  no-unused-vars`

**Comment by djmtype** [comment]
Now it's working? I had to reset Apache. And I used the original watch task, but specifying php instead of html for my purpose. 

```
gulp.task('watch', function() {
  browserSync.init({
    files: ['*.php'],
    server: {
        baseDir: "./"
    }
    //files: ['{lib,templates}/**/*.php', '*.php'],
    //proxy: config.devUrl,
    //snippetOptions: {
    //  whitelist: ['/wp-admin/admin-ajax.php'],
    //  blacklist: ['/wp-admin/**']
    //}
  });
```

**Comment by djmtype** [comment]
Just to clarify, this seems to be working for watching php files. 

```
browserSync.init({
    files: ['*.php'],
    proxy: manifest.config.devUrl
  });
```

The `devUrl` should of course be defined in manifest.json
