### ISSUE TITLE
Gulp Production

### ISSUE THREAD

**Issue by djmtype** [asuh/sage-starter#5]
Running `gulp --production` generates the assets with random characters appended to the file, however, the links to those files are broken when running `gulp --production watch`. Do we have to manually included the assets.json file in our page, then how? Or is there something else I'm missing?

**Comment by asuh** [comment]
Sage Starter stripped out most dynamic processing on purpose, including everything PHP which is how Sage can rewrite the CSS and JS on the fly. 

So you have two options:
- Use JS or your server-side solution to re-apply the same method for the production files
- Manually update the HTML pages that are broken

Hope this helps
